site_name: SCUFF-EM documentation
site_author: Homer Reid
site_favicon: scuffEM.ico

repo_url: https://github.com/homerreid/scuff-em/

theme_dir: 'scuff-em-mkdocs-theme'

python:
   version: 2 # for unicode
   setup_py_install: True

markdown_extensions:
    - wikilinks
    - toc:
        title: Table of Contents
    - attr_list
    - fenced_code
    - mdx_math:
        enable_dollar_delimiter: True

extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','mathjaxhelper.js']

pages:
- SCUFF-EM documentation: 'index.md'
- Examples:
    - 'Mie scattering':                           'examples/MieScattering/MieScattering.md'
    - 'Electrostatics of a spherical dielectric shell':   'examples/DielectricShell/DielectricShell.md'
    - 'Spatially-resolved study of plane-wave transmission through an infinite-area thin dielectric film':   'examples/ThinFilm/ThinFilm.md'
    - 'Imaging diffraction patterns of discs, disc arrays, and hole arrays in metal screens': 'examples/DiffractionPatterns/DiffractionPatterns.md'
    - 'Casimir forces in a compact geometry':     'examples/CubeTorus.md'
    - 'Casimir forces in a 1D extended geometry': 'examples/SiliconBeams/SiliconBeams.md'
    - 'Casimir forces in a 2D extended geometry': 'examples/SiliconSlabs/SiliconSlabs.md'
    - 'Casimir-Polder potentials in dielectric nanostructures': 'examples/NanostructureCasimirPolder/NanostructureCasimirPolder.md'
    - 'Thermal radiation, heat transfer, and non-equilibrium Casimir forces between silicon dioxide spheres': 'examples/SiO2Spheres/SiO2Spheres.md'
    - 'Spatial distribution of heat flux from a warm tip over a cold substrate': 'examples/TipSubstrate/TipSubstrate.md'
    - 'LDOS and dyadic Green functions above an infinite aluminum half-space': 'examples/HalfSpaceLDOS/HalfSpaceLDOS.md'
    - 'Electrostatic polarizability of platonic solids': 'examples/PlatonicSolids/PlatonicSolids.md'
    - 'Capacitance of two-body capacitors': 'examples/TwoBodyCapacitors/TwoBodyCapacitors.md'
    - 'Capacitance of a PCB stripline trace': 'examples/StriplineCapacitor/StriplineCapacitor.md'
    - 'Implicit handling of multilayer dielectric substrates': 'examples/ImplicitSubstrate/ImplicitSubstrate.md'
- General reference:
    - 'Top-level overview':        'reference/TopLevel.md'
    - 'Installation':              'reference/Installing.md'
    - 'Geometry descriptions':     'reference/Geometries.md'
    - 'Material designations':     'reference/Materials.md'
    - 'Geometric transformations': 'reference/Transformations.md'
    - 'Incident fields':           'reference/IncidentFields.md'
    - 'Brillouin zone integration': 'reference/BrillouinZoneIntegration.md'
    - 'FAQ':                       'reference/FAQ.md'
- Command-line application reference:
    - 'General command-line reference': 'applications/GeneralReference.md'
    - 'scuff-scatter':         'applications/scuff-scatter/scuff-scatter.md'
    - 'scuff-transmission':    'applications/scuff-transmission/scuff-transmission.md'
    - 'scuff-ldos':            'applications/scuff-ldos/scuff-ldos.md'
    - 'scuff-tmatrix':         'applications/scuff-tmatrix/scuff-tmatrix.md'
    - 'scuff-cas3D':           'applications/scuff-cas3D/scuff-cas3D.md'
    - 'scuff-caspol':          'applications/scuff-caspol/scuff-caspol.md'
    - 'scuff-neq':             'applications/scuff-neq/scuff-neq.md'
    - 'scuff-RF':              'applications/scuff-RF/scuff-RF.md'
    - 'scuff-static':          'applications/scuff-static/scuff-static.md'
    - 'scuff-analyze':         'applications/scuff-analyze/scuff-analyze.md'
    - 'scuff-integrate':       'applications/scuff-integrate/scuff-integrate.md'
- Validation tests:
    - 'Overview of the test suite':                                        'tests/Overview.md'
    - 'Mie scattering':                                                    'tests/MieScattering/MieScattering.md'
    - 'Fresnel scattering':                                                'tests/FresnelScattering/FresnelScattering.md'
    - 'Equilibrium Casimir forces between spheres':                        'tests/CasimirSpheres/CasimirSpheres.md'
    - 'Equilibrium Casimir forces between plates':                         'tests/CasimirPlates/CasimirPlates.md'
    - 'Equilibrium Casimir-Polder potential near a sphere':                'tests/CPSphere/CPSphere.md'
    - 'Equilibrium Casimir-Polder potential near a plate':                 'tests/CPPlate/CPPlate.md'
    - 'Heat transfer and non-equilibrium Casimir forces between spheres':  'tests/NEQSpheres/NEQSpheres.md'
    - 'Low-level tests of the core library':                               'tests/libscuff/libscuff.md'
- API reference:  
    - 'libscuff':              'API/libscuff.md'
- For developers:
    - 'Implementation':                        'forDevelopers/Implementation.md'
    - 'Data Structures':                       'forDevelopers/DataStructures.md'
    - 'Documentation':                         'forDevelopers/Documentation.md'
    - 'Code for computing singular integrals': 'forDevelopers/SingularIntegrals.md'
